---
version: 2
jobs:
  eclint:
    working_directory: ~/docker-eclint/
    docker:
      - image: qima/eclint:circleci-2.8.1-f83022d
    steps:
      - checkout
      - run:
          name: Validate Editor Config rules
          command: |
            set -x
            ls -l
            git ls-files
            eclint check $(git ls-files)
  docker-build:
    docker:
      - image: circleci/golang:1.11.5-stretch-node-browsers-legacy
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build-exec
          command: |
            set -x
            docker version
            make build
      - run:
          name: build-circleci
          command: |
            set -x
            docker version
            make build-circleci


workflows:
  version: 2
  workflow:
    jobs:
    - eclint
    - docker-build:
        requires:
            - eclint
