---
version: 2
jobs:
  eclint:
    working_directory: ~/docker-eclint/
    docker:
      - image: qima/eclint:circleci-2.8.1-f83022d
    steps:
      - checkout
      - run:
          name: Validate Editor Config rules
          command: |
            ls -l
            eclint check
      # - run:
      #     command: |  # Init and test TF plan
      #       terraform init
      #       terraform plan

workflows:
  version: 2
  workflow:
    jobs:
    - eclint
