---
version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.4
jobs:
  eclint:
    working_directory: ~/docker-eclint/
    docker:
      - image: qima/eclint:circleci-2.8.1-440a5cb
    steps:
      - checkout
      - run:
          name: Validate Editor Config rules
          command: |
            set -x
            ls -l
            git ls-files
            eclint check $(git ls-files)
  docker-build:
    docker:
      - image: circleci/golang:1.11.5-stretch-node
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build-exec
          command: |
            set -x
            docker version
            make build
            mkdir -p workspace
            echo "Save exec docker image for potential further push"
            docker image save $(make print-img-name):$(make print-exec-version) \
              -o workspace/$(make print-img-safe-name)--$(make print-exec-version)
            docker image save $(make print-img-name):$(make print-exec-latest) \
              -o workspace/$(make print-img-safe-name)--$(make print-exec-latest)
      - run:
          name: build-circleci
          command: |
            set -x
            docker version
            make build-circleci
            echo "Save circleci docker image for potential further push"
            docker image save $(make print-img-name):$(make print-circleci-version) \
              -o workspace/$(make print-img-safe-name)--$(make print-circleci-version)
            docker image save $(make print-img-name):$(make print-circleci-latest) \
              -o workspace/$(make print-img-safe-name)--$(make print-circleci-latest)
      - persist_to_workspace:
          root: workspace
          paths:
            - "*"
  docker-push-exec:
    docker:
      - image: circleci/golang:1.11.5-stretch-node
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - docker-publish/check
      - run:
          name: push-exec
          command: |
            set -x
            echo "Loading images from workspace"
            docker load -i /tmp/workspace/$(make print-img-safe-name)--$(make print-exec-version)
            docker load -i /tmp/workspace/$(make print-img-safe-name)--$(make print-exec-latest)
            docker image ls
            echo "Push to registry"
            make push push-latest
  docker-push-circleci:
    docker:
      - image: circleci/golang:1.11.5-stretch-node
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - docker-publish/check
      - run:
          name: push-circleci
          command: |
            set -x
            echo "Loading images from workspace"
            docker load -i /tmp/workspace/$(make print-img-safe-name)--$(make print-circleci-version)
            docker load -i /tmp/workspace/$(make print-img-safe-name)--$(make print-circleci-latest)
            docker image ls
            echo "Push to registry"
            make push-circleci push-circleci-latest

workflows:
  version: 2
  workflow:
    jobs:
    - eclint
    - docker-build:
        requires:
          - eclint
    - docker-push-exec:
        requires:
          - docker-build
        filters:
          branches:
            only:
              - master
              - provide_makefile
    - docker-push-circleci:
        requires:
          - docker-push-exec
        filters:
          branches:
            only:
              - master
              - provide_makefile
